name: PerfAI Test Actions
description: Active Performance for APIs (public, mobile, & web)
author: PerfAI, Inc.
branding:
  icon: activity
  color: blue
      
inputs:
  apiSpecURL:
    description: OpenAPI-Specification/Swagger URL
    required: true
  apiBasePath:
    description: API Base Path
    required: true
  authUrl:
    description: Token Authentication URL
    required: true
  authBody:
    description: Authentication Body JSON/Data
    required: true
  licenseKey:
    description: A code or token that allows the user to identify him/herself as a legal customer 
    required: false
    
outputs:
  report:
    description: Displays performance report
    
runs:
  using: "composite"
  steps:
    - run: docker run  -t -e apiSpecURL=${{ inputs.apiSpecURL }} -e apiBasePath=${{ inputs.apiBasePath }} -e authUrl=${{ inputs.authUrl }} -e authBody=${{ inputs.authBody }} ghcr.io/perfai-inc/perfai-engine:main
      shell: bash



# runs:
#   using: 'docker'
#   image: 'docker://ghcr.io/perfai-inc/perfai-engine:main' -e ${{ inputs.apiSpecURL }} -e ${{ inputs.apiBasePath }} 
#   args:
#     - ${{ inputs.apiSpecURL }}
#     - ${{ inputs.apiBasePath }}
#     - ${{ inputs.authUrl }}
#     - ${{ inputs.authBody }}
    
